/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package diary3.financemanager;

import diary3.Home;
import diary3.User;
import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.awt.event.MouseEvent;
import java.util.Date;
import java.util.StringTokenizer;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.ListCellRenderer;
import javax.swing.UIManager;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.MutableTreeNode;

/**
 *
 * @author Mahe
 */
public class FinanceManager extends javax.swing.JPanel {

    FinanceManagerAgent fma;
    User USER;

    public void setUSER(User USER) {
        this.USER = USER;
        fma = new FinanceManagerAgent(USER);
        DefaultListModel d = new DefaultListModel();
        FinanceEntry[] entries = new FinanceEntry[fma.financeEntries.size()];
        System.out.println("entries : " + entries.length);
        for (int i = 0; i < entries.length; i++) {
            entries[i] = fma.financeEntries.get(i);
        }
        ListCellRenderer e = new ListCellRenderer() {

            @Override
            public Component getListCellRendererComponent(JList list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
                FinanceEntry f = (FinanceEntry) value;
                JLabel p = new JLabel();
                p.setText(f.tag);
                p.setFont(new Font("Segoe UI Semilight", 0, 11));
                p.setToolTipText(f.toString());
                p.setBackground(jList1.getSelectionBackground());
                return p;
            }
        };
        for (int i = 0; i < entries.length; i++) {
            d.addElement(entries[i]);
            System.out.println(entries[i]);
        }
        jList1.setModel(d);
        jList1.setCellRenderer(e);
    }

    /**
     * Creates new form FinanceManager
     */
    public FinanceManager() {
        initComponents();
        floater.setBounds(floater.getX(), floater.getY(), deskPane.getWidth(), floater.getHeight());
        floater.hide();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        deskPane = new javax.swing.JDesktopPane();
        floater = new javax.swing.JPanel();
        menu = new javax.swing.JTabbedPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        userMenu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        floaterUserNameDisplay = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jLabel2 = new javax.swing.JLabel();
        date = new javax.swing.JComboBox();
        month = new javax.swing.JComboBox();
        year = new javax.swing.JComboBox();
        financeEntryViewer = new javax.swing.JInternalFrame();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        dateEntryView = new javax.swing.JTextField();
        monthEntryView = new javax.swing.JTextField();
        yearEntryView = new javax.swing.JTextField();
        tagEntryView = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        amountEntryView = new javax.swing.JTextField();
        dORcEntryView = new javax.swing.JComboBox();
        add10 = new javax.swing.JButton();
        add20 = new javax.swing.JButton();
        add50 = new javax.swing.JButton();
        add100 = new javax.swing.JButton();
        add500 = new javax.swing.JButton();
        add1000 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        descriptionEntryView = new javax.swing.JTextPane();
        submitEntryView = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        hoursTicker = new javax.swing.JSpinner();
        minutesTicker = new javax.swing.JSpinner();
        secondsTicker = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();

        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });

        deskPane.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                deskPaneMouseMoved(evt);
            }
        });

        floater.setBackground(new java.awt.Color(249, 249, 249));
        floater.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Menu", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.BELOW_BOTTOM, new java.awt.Font("Segoe UI Semilight", 0, 12), new java.awt.Color(102, 102, 102))); // NOI18N
        floater.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        floater.setMinimumSize(new java.awt.Dimension(650, 0));
        floater.setPreferredSize(new java.awt.Dimension(887, 0));
        floater.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                floaterMouseExited(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                floaterMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                floaterMouseReleased(evt);
            }
        });
        floater.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                floaterMouseDragged(evt);
            }
        });

        menu.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        menu.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        menu.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                menuMouseWheelMoved(evt);
            }
        });

        userMenu.setBackground(new java.awt.Color(249, 249, 249));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diary3/resources/config-users.png"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        floaterUserNameDisplay.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        floaterUserNameDisplay.setText("Guest");

        jToggleButton1.setText("Pin");

        javax.swing.GroupLayout userMenuLayout = new javax.swing.GroupLayout(userMenu);
        userMenu.setLayout(userMenuLayout);
        userMenuLayout.setHorizontalGroup(
            userMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(floaterUserNameDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, 663, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToggleButton1)
                .addContainerGap())
        );
        userMenuLayout.setVerticalGroup(
            userMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(userMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(userMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(floaterUserNameDisplay)
                        .addComponent(jToggleButton1))
                    .addComponent(jLabel1))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jScrollPane4.setViewportView(userMenu);

        menu.addTab("User", jScrollPane4);
        menu.addTab("Management", jScrollPane6);

        javax.swing.GroupLayout floaterLayout = new javax.swing.GroupLayout(floater);
        floater.setLayout(floaterLayout);
        floaterLayout.setHorizontalGroup(
            floaterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, 638, Short.MAX_VALUE)
        );
        floaterLayout.setVerticalGroup(
            floaterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
        );

        deskPane.add(floater);
        floater.setBounds(0, 0, 650, 0);

        jInternalFrame1.setIconifiable(true);
        jInternalFrame1.setResizable(true);
        jInternalFrame1.setTitle("Finance Entries");
        jInternalFrame1.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jInternalFrame1.setVisible(true);

        jList1.setFont(new java.awt.Font("Segoe UI Semilight", 0, 11)); // NOI18N
        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(jList1);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Filter : ");

        date.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        date.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "---" }));
        date.setSelectedIndex(31);
        date.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                dateItemStateChanged(evt);
            }
        });

        month.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        month.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec", "----" }));
        month.setSelectedIndex(12);
        month.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                monthItemStateChanged(evt);
            }
        });

        year.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        year.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "------", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014" }));
        year.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                yearItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(month, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(month, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        deskPane.add(jInternalFrame1);
        jInternalFrame1.setBounds(30, 20, 280, 360);

        financeEntryViewer.setResizable(true);
        financeEntryViewer.setTitle("Finance Entry Viewer");
        financeEntryViewer.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        financeEntryViewer.setVisible(true);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel3.setText("Tag :");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel4.setText("Date :");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel5.setText("Month :");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel6.setText("Year :");

        dateEntryView.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        dateEntryView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateEntryViewActionPerformed(evt);
            }
        });

        monthEntryView.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N

        yearEntryView.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N

        tagEntryView.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel7.setText("Amount :");

        amountEntryView.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        amountEntryView.setText("0.0");
        amountEntryView.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                amountEntryViewCaretUpdate(evt);
            }
        });

        dORcEntryView.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        dORcEntryView.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Debit", "Credit" }));

        add10.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        add10.setText("10");
        add10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                add10MouseClicked(evt);
            }
        });
        add10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add10ActionPerformed(evt);
            }
        });

        add20.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        add20.setText("20");
        add20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                add20MouseClicked(evt);
            }
        });
        add20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add20ActionPerformed(evt);
            }
        });

        add50.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        add50.setText("50");
        add50.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                add50MouseClicked(evt);
            }
        });
        add50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add50ActionPerformed(evt);
            }
        });

        add100.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        add100.setText("100");
        add100.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                add100MouseClicked(evt);
            }
        });
        add100.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add100ActionPerformed(evt);
            }
        });

        add500.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        add500.setText("500");
        add500.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                add500MouseClicked(evt);
            }
        });
        add500.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add500ActionPerformed(evt);
            }
        });

        add1000.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        add1000.setText("1000");
        add1000.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                add1000MouseClicked(evt);
            }
        });
        add1000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add1000ActionPerformed(evt);
            }
        });

        descriptionEntryView.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        jScrollPane1.setViewportView(descriptionEntryView);

        submitEntryView.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        submitEntryView.setText("Submit");
        submitEntryView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitEntryViewActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        jLabel8.setText("Time :");

        hoursTicker.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        hoursTicker.setModel(new javax.swing.SpinnerNumberModel(0, 0, 23, 1));

        minutesTicker.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        minutesTicker.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 1));

        secondsTicker.setFont(new java.awt.Font("Segoe UI Light", 0, 11)); // NOI18N
        secondsTicker.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 1));

        jLabel9.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        jLabel9.setText("Unlocked");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout financeEntryViewerLayout = new javax.swing.GroupLayout(financeEntryViewer.getContentPane());
        financeEntryViewer.getContentPane().setLayout(financeEntryViewerLayout);
        financeEntryViewerLayout.setHorizontalGroup(
            financeEntryViewerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(financeEntryViewerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(financeEntryViewerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(financeEntryViewerLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tagEntryView))
                    .addGroup(financeEntryViewerLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dateEntryView, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(monthEntryView, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(yearEntryView))
                    .addGroup(financeEntryViewerLayout.createSequentialGroup()
                        .addGroup(financeEntryViewerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(add10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(financeEntryViewerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(financeEntryViewerLayout.createSequentialGroup()
                                .addComponent(add20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(add50)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(add100)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(add500)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(add1000)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(financeEntryViewerLayout.createSequentialGroup()
                                .addComponent(amountEntryView)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dORcEntryView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, financeEntryViewerLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hoursTicker, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(minutesTicker)
                        .addGap(4, 4, 4)
                        .addComponent(secondsTicker, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(submitEntryView)))
                .addContainerGap())
        );
        financeEntryViewerLayout.setVerticalGroup(
            financeEntryViewerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(financeEntryViewerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(financeEntryViewerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tagEntryView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(financeEntryViewerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(dateEntryView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(monthEntryView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yearEntryView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(financeEntryViewerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(amountEntryView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dORcEntryView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(financeEntryViewerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add10)
                    .addComponent(add20)
                    .addComponent(add50)
                    .addComponent(add100)
                    .addComponent(add500)
                    .addComponent(add1000))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(financeEntryViewerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitEntryView)
                    .addComponent(jLabel8)
                    .addComponent(hoursTicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minutesTicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(secondsTicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        deskPane.add(financeEntryViewer);
        financeEntryViewer.setBounds(340, 20, 380, 360);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(deskPane, javax.swing.GroupLayout.DEFAULT_SIZE, 788, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(deskPane, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void floaterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_floaterMouseExited
        // TODO add your handling code here:
        System.out.println(evt.getY());
        if (evt.getY() > floater.getHeight() && !jToggleButton1.isSelected()) {
            floater.hide();
        }
        repaint();
    }//GEN-LAST:event_floaterMouseExited

    private void menuMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_menuMouseWheelMoved
        // TODO add your handling code here:
        int r = (int) ((Math.abs(evt.getUnitsToScroll()) / evt.getUnitsToScroll()));
        r = (menu.getSelectedIndex() + r) % menu.getTabCount();
        System.out.println(r);
        if (r >= 0) {
            menu.setSelectedIndex(r);
        } else {
            menu.setSelectedIndex(menu.getTabCount() + r);
        }
    }//GEN-LAST:event_menuMouseWheelMoved

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseMoved
    int floaterHeight = 220;
    private void deskPaneMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deskPaneMouseMoved
        // TODO add your handling code here:
        repaint();
        floater.setBounds(floater.getX(), floater.getY(), deskPane.getWidth(), floaterHeight);
        if (!floater.isVisible()) {
            floater.setVisible(evt.getY() < 10);
        } else {
            floater.setVisible(evt.getY() < floater.getHeight());
        }
        if (jToggleButton1.isSelected()) {
            floater.show();
        }
    }//GEN-LAST:event_deskPaneMouseMoved

    private void floaterMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_floaterMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_floaterMouseDragged
    int count = 0;
    long last = 0;
    Color lastbg = new Color(249, 249, 249);
    private void floaterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_floaterMouseClicked
        // TODO add your handling code here:
        if (count == 0) {
            count = 1;
            last = System.currentTimeMillis();
        } else if (count == 1) {
            long news = System.currentTimeMillis();
            if (last - news < 1000) {
                lastbg = floater.getBackground();
                floater.setBackground(Color.lightGray);
            }
        }
        deskPane.setBackground(null);
    }//GEN-LAST:event_floaterMouseClicked

    private void floaterMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_floaterMouseReleased
        // TODO add your handling code here:
        floater.setBackground(lastbg);
        System.out.println(lastbg);
        count = 0;
        System.out.println("Released!");
    }//GEN-LAST:event_floaterMouseReleased

    public void sortOutEntries() {
        fma.readEntries();
        FinanceEntry[] entries = new FinanceEntry[fma.financeEntries.size()];
        System.out.println("Total Entries : " + entries.length);
        for (int i = 0; i < entries.length; i++) {
            entries[i] = fma.financeEntries.get(i);
        }
            int da = date.getSelectedIndex();
            String m = (String) month.getSelectedItem();
            int yr = year.getSelectedIndex();
            Vector monthfilter = new Vector();
            for (int i = 0; i < entries.length; i++) {
                FinanceEntry f = entries[i];
                if (m.contains("---")) {
                    monthfilter.addElement(f);
                    System.out.println("MWild : " + f.date);
                } else {
                    if (f.date.contains(m)) {
                        monthfilter.addElement(f);
                        System.out.println("MFilter : " + f.date);
                    }
                }
            }
            System.out.println(monthfilter);
            int n = monthfilter.size();
            System.out.println("MonthFilter Count : " + n);
            Vector datefilter = new Vector();
            for (int i = 0; i < n; i++) {
                FinanceEntry f = (FinanceEntry) monthfilter.get(i);
                if (da == 31) {
                    datefilter.addElement(f);
                    System.out.println(i + " DWild : " + f.date);
                } else {
                    System.out.println("else date");
                    System.out.println(new Date(f.date).getDate() + " : " + (da + 1));
                    if (new Date(f.date).getDate() == da + 1) {
                        datefilter.addElement(f);
                        System.out.println(i + " DFilter : " + f.date);
                    }
                }
            }
            System.out.println(datefilter);
            Vector yearfilter = new Vector();
            for (int i = 0; i < datefilter.size(); i++) {
                FinanceEntry f = (FinanceEntry) datefilter.elementAt(i);
                if (yr == 0) {
                    yearfilter.addElement(f);
                    System.out.println("YWild : " + f.date);
                } else {
                    if (f.date.contains((String) year.getSelectedItem())) {
                        yearfilter.addElement(f);
                        System.out.println("YFilter : " + f.date);
                    }
                }
            }
            System.out.println("YearFilter count : " + yearfilter.size());
            System.out.println(yearfilter);
            DefaultListModel ff = new DefaultListModel();
            for (int i = 0; i < yearfilter.size(); i++) {
                FinanceEntry fe = (FinanceEntry) yearfilter.elementAt(i);
                ff.addElement(fe);
            }
            jList1.setModel(ff);
            jList1.repaint();
    }

    private void dateEntryViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateEntryViewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateEntryViewActionPerformed

    private void add10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add10ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_add10ActionPerformed

    private void add20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add20ActionPerformed

    }//GEN-LAST:event_add20ActionPerformed

    private void add50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add50ActionPerformed

    }//GEN-LAST:event_add50ActionPerformed

    private void add100ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add100ActionPerformed

    }//GEN-LAST:event_add100ActionPerformed

    private void add500ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add500ActionPerformed

    }//GEN-LAST:event_add500ActionPerformed

    private void add1000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add1000ActionPerformed

    }//GEN-LAST:event_add1000ActionPerformed

    private void amountEntryViewCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_amountEntryViewCaretUpdate
        // TODO add your handling code here:

    }//GEN-LAST:event_amountEntryViewCaretUpdate

    private void add10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add10MouseClicked
        // TODO add your handling code here:
        try {
            double value = Double.parseDouble(amountEntryView.getText());
            if (evt.getButton() == MouseEvent.BUTTON1) {
                amountEntryView.setText((value + 10) + "");
            } else if (evt.getButton() == MouseEvent.BUTTON3) {
                amountEntryView.setText((value - 10) + "");
            }
        } catch (NumberFormatException e) {
            amountEntryView.setText("Invalid Entry : " + amountEntryView.getText());
        }
    }//GEN-LAST:event_add10MouseClicked

    private void add20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add20MouseClicked
        // TODO add your handling code here:
        try {
            double value = Double.parseDouble(amountEntryView.getText());
            if (evt.getButton() == MouseEvent.BUTTON1) {
                amountEntryView.setText((value + 20) + "");
            } else if (evt.getButton() == MouseEvent.BUTTON3) {
                amountEntryView.setText((value - 20) + "");
            }
        } catch (NumberFormatException e) {
            amountEntryView.setText("Invalid Entry : " + amountEntryView.getText());
        }
    }//GEN-LAST:event_add20MouseClicked

    private void add50MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add50MouseClicked
        // TODO add your handling code here:
        try {
            double value = Double.parseDouble(amountEntryView.getText());
            if (evt.getButton() == MouseEvent.BUTTON1) {
                amountEntryView.setText((value + 50) + "");
            } else if (evt.getButton() == MouseEvent.BUTTON3) {
                amountEntryView.setText((value - 50) + "");
            }
        } catch (NumberFormatException e) {
            amountEntryView.setText("Invalid Entry : " + amountEntryView.getText());
        }
    }//GEN-LAST:event_add50MouseClicked

    private void add100MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add100MouseClicked
        // TODO add your handling code here:
        try {
            double value = Double.parseDouble(amountEntryView.getText());
            if (evt.getButton() == MouseEvent.BUTTON1) {
                amountEntryView.setText((value + 100) + "");
            } else if (evt.getButton() == MouseEvent.BUTTON3) {
                amountEntryView.setText((value - 100) + "");
            }
        } catch (NumberFormatException e) {
            amountEntryView.setText("Invalid Entry : " + amountEntryView.getText());
        }
    }//GEN-LAST:event_add100MouseClicked

    private void add500MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add500MouseClicked
        // TODO add your handling code here:
        try {
            double value = Double.parseDouble(amountEntryView.getText());
            if (evt.getButton() == MouseEvent.BUTTON1) {
                amountEntryView.setText((value + 500) + "");
            } else if (evt.getButton() == MouseEvent.BUTTON3) {
                amountEntryView.setText((value - 500) + "");
            }
        } catch (NumberFormatException e) {
            amountEntryView.setText("Invalid Entry : " + amountEntryView.getText());
        }
    }//GEN-LAST:event_add500MouseClicked

    private void add1000MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add1000MouseClicked
        // TODO add your handling code here:
        try {
            double value = Double.parseDouble(amountEntryView.getText());
            if (evt.getButton() == MouseEvent.BUTTON1) {
                amountEntryView.setText((value + 1000) + "");
            } else if (evt.getButton() == MouseEvent.BUTTON3) {
                amountEntryView.setText((value - 1000) + "");
            }
        } catch (NumberFormatException e) {
            amountEntryView.setText("Invalid Entry : " + amountEntryView.getText());
        }
    }//GEN-LAST:event_add1000MouseClicked

    private void submitEntryViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitEntryViewActionPerformed
        // TODO add your handling code here:
        int year = Integer.parseInt(yearEntryView.getText());
        int month = Integer.parseInt(monthEntryView.getText());
        int date = Integer.parseInt(dateEntryView.getText());
        int hrs = (Integer) hoursTicker.getValue();
        int min = (Integer) minutesTicker.getValue();
        int sec = (Integer) secondsTicker.getValue();
        DefaultComboBoxModel d = (DefaultComboBoxModel) this.month.getModel();
        String hs = (hrs < 10) ? "0" + hrs : hrs + "";
        String ms = (min < 10) ? "0" + min : min + "";
        String ss = (sec < 10) ? "0" + sec : sec + "";

        String s = date + " " + d.getElementAt(month - 1) + " " + year + " " + hs + ":" + ms + ":" + ss;
        fma.addEntry(s, tagEntryView.getText(), Double.parseDouble(amountEntryView.getText()), (dORcEntryView.getSelectedIndex() == 0) ? 'd' : 'c', descriptionEntryView.getText());
        System.out.println("Added!");
        jLabel9.setText("Locked");
        submitEntryView.setEnabled(false);
        sortOutEntries();
    }//GEN-LAST:event_submitEntryViewActionPerformed

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        jLabel9.setText("Unlocked");
        submitEntryView.setEnabled(true);
        tagEntryView.setText("");
        dateEntryView.setText("");
        monthEntryView.setText("");
        yearEntryView.setText("");
        amountEntryView.setText("0.0");
        descriptionEntryView.setText("");
        dORcEntryView.setSelectedIndex(0);
        hoursTicker.setValue(0);
        minutesTicker.setValue(0);
        secondsTicker.setValue(0);
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
        // TODO add your handling code here:
        System.out.println(jList1.getSelectedValue().toString());
        StringTokenizer stt = new StringTokenizer(jList1.getSelectedValue().toString(), "|");
        String tag = stt.nextToken();
        String ds = stt.nextToken();
        double amt = Double.parseDouble(stt.nextToken());
        char c = stt.nextToken().charAt(0);
        String desc = stt.nextToken();
        FinanceEntry f = new FinanceEntry(ds, tag, amt, c, desc);
        tagEntryView.setText(f.tag);
        amountEntryView.setText(f.amount+"");
        dORcEntryView.setSelectedIndex((f.dORc=='d')?0:1);
        descriptionEntryView.setText(f.description);
        String date = f.date;
        Date dd = new Date(date);
        dateEntryView.setText(dd.getDate()+"");
        monthEntryView.setText((dd.getMonth()+1)+"");
        yearEntryView.setText((dd.getYear()+1900)+"");
        hoursTicker.setValue(dd.getHours());
        minutesTicker.setValue(dd.getMinutes());
        secondsTicker.setValue(dd.getSeconds());
        jLabel9.setText("Locked");
        submitEntryView.setEnabled(false);
    }//GEN-LAST:event_jList1ValueChanged

    private void dateItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_dateItemStateChanged
        // TODO add your handling code here:
        sortOutEntries();
    }//GEN-LAST:event_dateItemStateChanged

    private void monthItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_monthItemStateChanged
        // TODO add your handling code here:
        sortOutEntries();
    }//GEN-LAST:event_monthItemStateChanged

    private void yearItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_yearItemStateChanged
        // TODO add your handling code here:
        sortOutEntries();
    }//GEN-LAST:event_yearItemStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add10;
    private javax.swing.JButton add100;
    private javax.swing.JButton add1000;
    private javax.swing.JButton add20;
    private javax.swing.JButton add50;
    private javax.swing.JButton add500;
    private javax.swing.JTextField amountEntryView;
    private javax.swing.JComboBox dORcEntryView;
    private javax.swing.JComboBox date;
    private javax.swing.JTextField dateEntryView;
    private javax.swing.JTextPane descriptionEntryView;
    private javax.swing.JDesktopPane deskPane;
    private javax.swing.JInternalFrame financeEntryViewer;
    private javax.swing.JPanel floater;
    private javax.swing.JLabel floaterUserNameDisplay;
    private javax.swing.JSpinner hoursTicker;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTabbedPane menu;
    private javax.swing.JSpinner minutesTicker;
    private javax.swing.JComboBox month;
    private javax.swing.JTextField monthEntryView;
    private javax.swing.JSpinner secondsTicker;
    private javax.swing.JButton submitEntryView;
    private javax.swing.JTextField tagEntryView;
    private javax.swing.JPanel userMenu;
    private javax.swing.JComboBox year;
    private javax.swing.JTextField yearEntryView;
    // End of variables declaration//GEN-END:variables
}
