/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package diary3;

import com.alee.utils.swing.DelayFormatException;
import java.awt.AWTException;
import java.awt.Color;
import java.awt.Component;
import java.awt.Desktop;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.GraphicsEnvironment;
import java.awt.GridLayout;
import java.awt.Image;
import java.awt.Rectangle;
import java.awt.Robot;
import java.awt.event.KeyEvent;
import java.awt.event.MouseEvent;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.util.Date;
import java.util.StringTokenizer;
import java.util.Timer;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.DesktopManager;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.ListCellRenderer;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.event.ListDataListener;

/**
 *
 * @author Mahe
 */
public class DiaryView extends javax.swing.JFrame {

    Image bkgd;
    Timer deskChangerTimer;

    /**
     * Creates new form DiaryView
     */
    public DiaryView() {

        MenuChangerAction.DIARY = this;
        MenuChangerMouse.DIARY = this;
        initComponents();
        deskChangerTimer = new java.util.Timer();
        logInWindow.show();
        floater.hide();
        floater.setBounds(floater.getX(), floater.getY(), deskPane.getWidth(), 230);
        initEdit();
        setEditMenu("Edit");
        setEditMenu("None");
        try {
            r = new Robot();
        } catch (AWTException ex) {
            Logger.getLogger(DiaryView.class.getName()).log(Level.SEVERE, null, ex);
        }
        floater.setBounds(floater.getX(), floater.getY(), deskPane.getWidth(), floater.getHeight() + 30);
        logCalendar.months.setSelectedIndex(new Date().getMonth());
        logCalendar.years.setSelectedIndex(logCalendar.years.getModel().getSize() - 1);
        floaterLogInButton.setBackground(new Color(153, 255, 153));
        floaterLogInButton.setText("Log In");
        floaterLogInButton.setToolTipText("LOGIN");
        GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
        Rectangle r = ge.getMaximumWindowBounds();
        setBounds(r);
        floater.hide();
    }

    public void initEdit() {
        fontList.setCellRenderer(new ListCellRenderer() {
            @Override
            public Component getListCellRendererComponent(JList list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
                JLabel j = new JLabel(String.valueOf(value));
                j.setText((String) value);
                j.setOpaque(true);
                j.setBounds(0, 0, 0, 30);
                if (cellHasFocus) {
                    j.setBackground(new Color(238, 238, 238));
                } else if (isSelected) {
                    j.setBackground(new Color(240, 240, 240));
                }
                return j;
            }
        });
        GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
        Font[] fonts = ge.getAllFonts();
        DefaultListModel d = new DefaultListModel();
        for (int i = 0; i < fonts.length; i++) {
            d.addElement(fonts[i].getName());
        }
        fontList.setModel(d);
        fontList.repaint();
        fontList1.setModel(d);
        fontList1.repaint();
        floater.repaint();
        floater.hide();

        UIManager.LookAndFeelInfo[] ll = UIManager.getInstalledLookAndFeels();
        DefaultListModel dlm = new DefaultListModel();
        for (int i = 1; i < ll.length; i++) {
            dlm.addElement(ll[i].getClassName());
        }
        themes.setModel(dlm);
        logEditor.setBackground(Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        defaultEditMenu = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        fontSize = new javax.swing.JSpinner();
        foneType = new javax.swing.JComboBox();
        fontShow = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        fontList = new javax.swing.JList();
        deskEditMenu = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        themes = new javax.swing.JList();
        logEditMenu = new javax.swing.JPanel();
        logEditTab = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        fontSize1 = new javax.swing.JSpinner();
        foneType1 = new javax.swing.JComboBox();
        fontShow1 = new javax.swing.JLabel();
        jScrollPane12 = new javax.swing.JScrollPane();
        fontList1 = new javax.swing.JList();
        addLogButton = new javax.swing.JButton();
        fontColor1 = new javax.swing.JTextField();
        jButton13 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        addLogButton1 = new javax.swing.JButton();
        jScrollPane14 = new javax.swing.JScrollPane();
        htmlCodeEditor = new javax.swing.JTextPane();
        jToolBar1 = new javax.swing.JToolBar();
        jButton9 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jScrollPane11 = new javax.swing.JScrollPane();
        logEditor = new javax.swing.JEditorPane();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        home = new javax.swing.JPanel();
        biodata = new javax.swing.JPanel();
        bd_username = new javax.swing.JLabel();
        bd_first_name = new javax.swing.JLabel();
        bd_middle_name = new javax.swing.JLabel();
        bd_last_name = new javax.swing.JLabel();
        bd_gender = new javax.swing.JLabel();
        bd_dob = new javax.swing.JLabel();
        bd_address = new javax.swing.JLabel();
        bd_city = new javax.swing.JLabel();
        bd_region_province = new javax.swing.JLabel();
        bd_country = new javax.swing.JLabel();
        bd_pin_code = new javax.swing.JLabel();
        bd_phone_number = new javax.swing.JLabel();
        bd_mobile_number = new javax.swing.JLabel();
        bd_relationship_status = new javax.swing.JLabel();
        bd_brief = new javax.swing.JLabel();
        desk = new javax.swing.JPanel();
        deskPane = new javax.swing.JDesktopPane();
        floater = new javax.swing.JPanel();
        menu = new javax.swing.JTabbedPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        userMenu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        floaterLogInButton = new javax.swing.JButton();
        floaterUserNameDisplay = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        fileMenu = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        editMenu = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        managementMenu = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        calendar = new javax.swing.JInternalFrame();
        logCalendar = new diary3.DCalendar();
        jScrollPane10 = new javax.swing.JScrollPane();
        currentLogList = new javax.swing.JList();
        logInWindow = new javax.swing.JInternalFrame();
        jLabel2 = new javax.swing.JLabel();
        logInUserName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        logInUserPassword = new javax.swing.JPasswordField();
        logEditorWindow = new javax.swing.JInternalFrame();
        jLabel4 = new javax.swing.JLabel();
        titleView = new javax.swing.JTextField();
        jScrollPane15 = new javax.swing.JScrollPane();
        documentEditor1 = new diary3.DocumentEditor();
        documentsPane = new javax.swing.JTabbedPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        picturesPane = new javax.swing.JDesktopPane();
        jScrollPane7 = new javax.swing.JScrollPane();
        musicPane = new javax.swing.JDesktopPane();
        jScrollPane8 = new javax.swing.JScrollPane();
        Others = new javax.swing.JLayeredPane();
        jPanel5 = new javax.swing.JPanel();
        financeManager2 = new diary3.financemanager.FinanceManager();

        defaultEditMenu.setBackground(new java.awt.Color(249, 249, 249));

        jPanel1.setBackground(new java.awt.Color(249, 249, 249));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Font"));

        fontSize.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        fontSize.setModel(new javax.swing.SpinnerNumberModel(12, 8, 108, 2));
        fontSize.setName(""); // NOI18N
        fontSize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fontSizeMouseClicked(evt);
            }
        });

        foneType.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        foneType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Plain", "Bold", "Italic", "Bold/Italic" }));
        foneType.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                foneTypeItemStateChanged(evt);
            }
        });

        fontShow.setText("ABCDEF 123 abcdef");

        fontList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        fontList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                fontListValueChanged(evt);
            }
        });
        jScrollPane9.setViewportView(fontList);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(fontSize, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(foneType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 181, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(fontShow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fontSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(foneType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(fontShow, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE))
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout defaultEditMenuLayout = new javax.swing.GroupLayout(defaultEditMenu);
        defaultEditMenu.setLayout(defaultEditMenuLayout);
        defaultEditMenuLayout.setHorizontalGroup(
            defaultEditMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(defaultEditMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        defaultEditMenuLayout.setVerticalGroup(
            defaultEditMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(defaultEditMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        deskEditMenu.setBackground(new java.awt.Color(249, 249, 249));

        jPanel2.setBackground(new java.awt.Color(249, 249, 249));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Theme", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12))); // NOI18N

        themes.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                themesValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(themes);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 639, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout deskEditMenuLayout = new javax.swing.GroupLayout(deskEditMenu);
        deskEditMenu.setLayout(deskEditMenuLayout);
        deskEditMenuLayout.setHorizontalGroup(
            deskEditMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deskEditMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        deskEditMenuLayout.setVerticalGroup(
            deskEditMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deskEditMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        logEditMenu.setBackground(new java.awt.Color(249, 249, 249));

        logEditTab.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jPanel3.setBackground(new java.awt.Color(249, 249, 249));

        fontSize1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        fontSize1.setModel(new javax.swing.SpinnerNumberModel(12, 8, 108, 2));
        fontSize1.setName(""); // NOI18N
        fontSize1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fontSize1MouseClicked(evt);
            }
        });
        fontSize1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                fontSize1StateChanged(evt);
            }
        });
        fontSize1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                fontSize1PropertyChange(evt);
            }
        });

        foneType1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        foneType1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Plain", "Bold", "Italic", "Bold/Italic" }));
        foneType1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                foneType1ItemStateChanged(evt);
            }
        });

        fontShow1.setText("ABCDEF 123 abcdef");

        fontList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        fontList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                fontList1ValueChanged(evt);
            }
        });
        jScrollPane12.setViewportView(fontList1);

        addLogButton.setText("Add Log");
        addLogButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addLogButtonActionPerformed(evt);
            }
        });

        fontColor1.setText("black");
        fontColor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fontColor1ActionPerformed(evt);
            }
        });

        jButton13.setText("Insert Code (HTML)");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(fontSize1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(foneType1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(fontShow1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(fontColor1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 129, Short.MAX_VALUE)
                        .addComponent(addLogButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton13)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(addLogButton)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(fontSize1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(foneType1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(fontColor1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fontShow1, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton13))))
                    .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        logEditTab.addTab("Font", jPanel3);

        jPanel4.setBackground(new java.awt.Color(249, 249, 249));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("HTML Code"));

        addLogButton1.setText("Insert Code");
        addLogButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addLogButton1ActionPerformed(evt);
            }
        });

        jScrollPane14.setViewportView(htmlCodeEditor);

        jToolBar1.setBackground(new java.awt.Color(249, 249, 249));
        jToolBar1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        jButton9.setText("Image");
        jButton9.setToolTipText(" <img src=\"\" width=\"\" height=\"\" alt=\"\">");
        jButton9.setFocusable(false);
        jButton9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton9.setOpaque(false);
        jButton9.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton9);

        jButton8.setText("New Line");
        jButton8.setToolTipText(" <br>");
        jButton8.setFocusable(false);
        jButton8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton8.setOpaque(false);
        jButton8.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton8);

        jButton1.setText(" P ");
        jButton1.setToolTipText(" <p>  </p>");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setOpaque(false);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        jButton2.setText("Link");
        jButton2.setToolTipText(" <a href=\"\"> </a>");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setOpaque(false);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton2);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "h1", "h2", "h3", "h4", "h5", "h6" }));
        jComboBox1.setMaximumSize(new java.awt.Dimension(60, 20));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jToolBar1.add(jComboBox1);

        jButton10.setText("B");
        jButton10.setToolTipText(" <b> </b>");
        jButton10.setFocusable(false);
        jButton10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton10.setOpaque(false);
        jButton10.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton10);

        jButton11.setText("I");
        jButton11.setToolTipText(" <i> </i>");
        jButton11.setFocusable(false);
        jButton11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton11.setOpaque(false);
        jButton11.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton11);

        jButton12.setText("U");
        jButton12.setToolTipText(" <u> </u>");
        jButton12.setFocusable(false);
        jButton12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton12.setOpaque(false);
        jButton12.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton12);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addLogButton1)
                .addContainerGap())
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 713, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(addLogButton1)
                        .addGap(0, 65, Short.MAX_VALUE))
                    .addComponent(jScrollPane14)))
        );

        logEditTab.addTab("HTML Code", jPanel4);

        javax.swing.GroupLayout logEditMenuLayout = new javax.swing.GroupLayout(logEditMenu);
        logEditMenu.setLayout(logEditMenuLayout);
        logEditMenuLayout.setHorizontalGroup(
            logEditMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logEditTab)
        );
        logEditMenuLayout.setVerticalGroup(
            logEditMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logEditTab, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        logEditor.setName("logEditor"); // NOI18N
        logEditor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logEditorMouseClicked(evt);
            }
        });
        logEditor.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                logEditorMouseMoved(evt);
            }
        });
        jScrollPane11.setViewportView(logEditor);
        logEditor.addMouseListener(new MenuChangerMouse());

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Diary 3.0");
        setUndecorated(true);
        setOpacity(0.9F);

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseExited(evt);
            }
        });

        home.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        biodata.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Bio Data", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18))); // NOI18N
        biodata.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        bd_username.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        bd_username.setText("Username :");

        bd_first_name.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        bd_first_name.setText("First Name :");

        bd_middle_name.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        bd_middle_name.setText("Middle Name :");

        bd_last_name.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        bd_last_name.setText("Last Name :");

        bd_gender.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        bd_gender.setText("Gender :");

        bd_dob.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        bd_dob.setText("Date of Birth :");

        bd_address.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        bd_address.setText("Address :");

        bd_city.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        bd_city.setText("City :");

        bd_region_province.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        bd_region_province.setText("Region/Province :");

        bd_country.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        bd_country.setText("Country :");

        bd_pin_code.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        bd_pin_code.setText("Pin Code :");

        bd_phone_number.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        bd_phone_number.setText("Phone Number  :");

        bd_mobile_number.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        bd_mobile_number.setText("Mobile Number :");

        bd_relationship_status.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        bd_relationship_status.setText("Relationship Status :");

        bd_brief.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        bd_brief.setText("Brief :");

        javax.swing.GroupLayout biodataLayout = new javax.swing.GroupLayout(biodata);
        biodata.setLayout(biodataLayout);
        biodataLayout.setHorizontalGroup(
            biodataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(biodataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(biodataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bd_username)
                    .addComponent(bd_first_name)
                    .addComponent(bd_middle_name)
                    .addComponent(bd_last_name)
                    .addComponent(bd_gender)
                    .addComponent(bd_city)
                    .addComponent(bd_region_province)
                    .addComponent(bd_phone_number)
                    .addComponent(bd_mobile_number)
                    .addComponent(bd_pin_code)
                    .addComponent(bd_country)
                    .addComponent(bd_brief)
                    .addComponent(bd_relationship_status)
                    .addComponent(bd_dob)
                    .addComponent(bd_address))
                .addContainerGap(209, Short.MAX_VALUE))
        );
        biodataLayout.setVerticalGroup(
            biodataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(biodataLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bd_username)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bd_first_name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bd_middle_name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bd_last_name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bd_gender)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bd_dob)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bd_address)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bd_city)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bd_region_province)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bd_country)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bd_pin_code)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bd_phone_number)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bd_mobile_number)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bd_relationship_status)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bd_brief)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout homeLayout = new javax.swing.GroupLayout(home);
        home.setLayout(homeLayout);
        homeLayout.setHorizontalGroup(
            homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(biodata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(371, Short.MAX_VALUE))
        );
        homeLayout.setVerticalGroup(
            homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(biodata, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Home", home);

        desk.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                deskMouseMoved(evt);
            }
        });

        deskPane.setName("deskPane"); // NOI18N
        deskPane.setOpaque(false);
        deskPane.setSelectedFrame(logInWindow);
        deskPane.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                deskPaneMouseMoved(evt);
            }
        });

        floater.setBackground(new java.awt.Color(249, 249, 249));
        floater.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Menu", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.BELOW_BOTTOM, new java.awt.Font("Segoe UI Semilight", 0, 12), new java.awt.Color(102, 102, 102))); // NOI18N
        floater.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        floater.setMinimumSize(new java.awt.Dimension(650, 0));
        floater.setPreferredSize(new java.awt.Dimension(650, 0));
        floater.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                floaterMouseExited(evt);
            }
        });

        menu.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        menu.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        menu.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                menuMouseWheelMoved(evt);
            }
        });

        userMenu.setBackground(new java.awt.Color(249, 249, 249));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diary3/resources/config-users.png"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        floaterLogInButton.setBackground(new java.awt.Color(153, 255, 153));
        floaterLogInButton.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        floaterLogInButton.setText("Log In");
        floaterLogInButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                floaterLogInButtonMouseClicked(evt);
            }
        });
        floaterLogInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                floaterLogInButtonActionPerformed(evt);
            }
        });

        floaterUserNameDisplay.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        floaterUserNameDisplay.setText("Guest");

        jToggleButton1.setText("Pin");

        javax.swing.GroupLayout userMenuLayout = new javax.swing.GroupLayout(userMenu);
        userMenu.setLayout(userMenuLayout);
        userMenuLayout.setHorizontalGroup(
            userMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(userMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(userMenuLayout.createSequentialGroup()
                        .addGap(0, 432, Short.MAX_VALUE)
                        .addComponent(floaterLogInButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(userMenuLayout.createSequentialGroup()
                        .addComponent(floaterUserNameDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton1)))
                .addContainerGap())
        );
        userMenuLayout.setVerticalGroup(
            userMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(userMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(userMenuLayout.createSequentialGroup()
                        .addGroup(userMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(floaterUserNameDisplay)
                            .addComponent(jToggleButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(floaterLogInButton))
                    .addGroup(userMenuLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 27, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jScrollPane4.setViewportView(userMenu);

        menu.addTab("User", jScrollPane4);

        fileMenu.setBackground(new java.awt.Color(249, 249, 249));

        jButton7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diary3/resources/application-exit_1.png"))); // NOI18N
        jButton7.setText("Exit");
        jButton7.setContentAreaFilled(false);

        javax.swing.GroupLayout fileMenuLayout = new javax.swing.GroupLayout(fileMenu);
        fileMenu.setLayout(fileMenuLayout);
        fileMenuLayout.setHorizontalGroup(
            fileMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fileMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton7)
                .addContainerGap(464, Short.MAX_VALUE))
        );
        fileMenuLayout.setVerticalGroup(
            fileMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fileMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton7)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(fileMenu);

        menu.addTab("File", jScrollPane1);

        editMenu.setBackground(new java.awt.Color(249, 249, 249));

        javax.swing.GroupLayout editMenuLayout = new javax.swing.GroupLayout(editMenu);
        editMenu.setLayout(editMenuLayout);
        editMenuLayout.setHorizontalGroup(
            editMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 659, Short.MAX_VALUE)
        );
        editMenuLayout.setVerticalGroup(
            editMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 181, Short.MAX_VALUE)
        );

        jScrollPane5.setViewportView(editMenu);

        menu.addTab("Edit", jScrollPane5);

        managementMenu.setBackground(new java.awt.Color(249, 249, 249));
        managementMenu.setLayout(new java.awt.GridLayout(1, 0));

        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diary3/resources/folder-pictures.png"))); // NOI18N
        jButton3.setText("Pictures");
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        managementMenu.add(jButton3);

        jButton4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diary3/resources/advanced-directory.png"))); // NOI18N
        jButton4.setText("Others");
        jButton4.setContentAreaFilled(false);
        managementMenu.add(jButton4);

        jButton5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diary3/resources/folder-music.png"))); // NOI18N
        jButton5.setText("Music");
        jButton5.setContentAreaFilled(false);
        managementMenu.add(jButton5);

        jButton6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diary3/resources/folder-videos.png"))); // NOI18N
        jButton6.setText("Videos");
        jButton6.setContentAreaFilled(false);
        managementMenu.add(jButton6);

        jScrollPane6.setViewportView(managementMenu);

        menu.addTab("Management", jScrollPane6);

        javax.swing.GroupLayout floaterLayout = new javax.swing.GroupLayout(floater);
        floater.setLayout(floaterLayout);
        floaterLayout.setHorizontalGroup(
            floaterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, 638, Short.MAX_VALUE)
        );
        floaterLayout.setVerticalGroup(
            floaterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
        );

        deskPane.add(floater);
        floater.setBounds(0, 0, 650, 0);

        calendar.setIconifiable(true);
        calendar.setMaximizable(true);
        calendar.setResizable(true);
        calendar.setTitle("Calendar");
        calendar.setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/diary3/resources/emblem-calendar.png"))); // NOI18N
        calendar.setVisible(false);

        currentLogList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                currentLogListMouseClicked(evt);
            }
        });
        currentLogList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                currentLogListValueChanged(evt);
            }
        });
        jScrollPane10.setViewportView(currentLogList);

        javax.swing.GroupLayout calendarLayout = new javax.swing.GroupLayout(calendar.getContentPane());
        calendar.getContentPane().setLayout(calendarLayout);
        calendarLayout.setHorizontalGroup(
            calendarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logCalendar, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
            .addComponent(jScrollPane10)
        );
        calendarLayout.setVerticalGroup(
            calendarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(calendarLayout.createSequentialGroup()
                .addComponent(logCalendar, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        deskPane.add(calendar);
        calendar.setBounds(20, 30, 390, 430);
        deskPane.setLayer(calendar, javax.swing.JLayeredPane.MODAL_LAYER);

        logInWindow.setTitle("Login : Diary 3.0");
        logInWindow.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        logInWindow.setMaximumSize(new java.awt.Dimension(200, 170));
        logInWindow.setMinimumSize(new java.awt.Dimension(200, 170));
        logInWindow.setPreferredSize(new java.awt.Dimension(200, 170));
        try {
            logInWindow.setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        logInWindow.setVisible(false);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Log In :");

        logInUserName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        logInUserName.setName("username"); // NOI18N
        logInUserName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                logInUserNameKeyPressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Password :");

        logInUserPassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        logInUserPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                logInUserPasswordKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout logInWindowLayout = new javax.swing.GroupLayout(logInWindow.getContentPane());
        logInWindow.getContentPane().setLayout(logInWindowLayout);
        logInWindowLayout.setHorizontalGroup(
            logInWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logInWindowLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(logInWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logInUserName)
                    .addGroup(logInWindowLayout.createSequentialGroup()
                        .addGroup(logInWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(0, 99, Short.MAX_VALUE))
                    .addComponent(logInUserPassword))
                .addContainerGap())
        );
        logInWindowLayout.setVerticalGroup(
            logInWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logInWindowLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logInUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logInUserPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        logInUserName.addMouseListener(new MenuChangerMouse());

        deskPane.add(logInWindow);
        logInWindow.setBounds(370, 260, 200, 170);

        logEditorWindow.setIconifiable(true);
        logEditorWindow.setMaximizable(true);
        logEditorWindow.setResizable(true);
        logEditorWindow.setTitle("LogEditor");
        logEditorWindow.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        logEditorWindow.setVisible(true);

        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel4.setText("Title :");
        jLabel4.setMaximumSize(new java.awt.Dimension(40, 30));
        jLabel4.setMinimumSize(new java.awt.Dimension(40, 30));

        titleView.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        titleView.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        titleView.setMinimumSize(new java.awt.Dimension(2, 30));
        titleView.setPreferredSize(new java.awt.Dimension(2, 30));

        jScrollPane15.setViewportView(documentEditor1);

        javax.swing.GroupLayout logEditorWindowLayout = new javax.swing.GroupLayout(logEditorWindow.getContentPane());
        logEditorWindow.getContentPane().setLayout(logEditorWindowLayout);
        logEditorWindowLayout.setHorizontalGroup(
            logEditorWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logEditorWindowLayout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(titleView, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE))
            .addComponent(jScrollPane15)
        );
        logEditorWindowLayout.setVerticalGroup(
            logEditorWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logEditorWindowLayout.createSequentialGroup()
                .addGroup(logEditorWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(titleView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        deskPane.add(logEditorWindow);
        logEditorWindow.setBounds(250, 20, 450, 360);
        deskPane.setLayer(logEditorWindow, javax.swing.JLayeredPane.MODAL_LAYER);

        javax.swing.GroupLayout deskLayout = new javax.swing.GroupLayout(desk);
        desk.setLayout(deskLayout);
        deskLayout.setHorizontalGroup(
            deskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(deskPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 734, Short.MAX_VALUE)
        );
        deskLayout.setVerticalGroup(
            deskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(deskPane, javax.swing.GroupLayout.DEFAULT_SIZE, 532, Short.MAX_VALUE)
        );

        deskPane.addMouseListener(new MenuChangerMouse());

        jTabbedPane1.addTab("Diary Desk", desk);

        documentsPane.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                documentsPaneMouseWheelMoved(evt);
            }
        });

        jScrollPane3.setViewportView(picturesPane);

        documentsPane.addTab("Pictures", jScrollPane3);

        jScrollPane7.setViewportView(musicPane);

        documentsPane.addTab("Music", jScrollPane7);

        jScrollPane8.setViewportView(Others);

        documentsPane.addTab("Others", jScrollPane8);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(financeManager2, javax.swing.GroupLayout.DEFAULT_SIZE, 729, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(financeManager2, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)
        );

        documentsPane.addTab("Finance", jPanel5);

        jTabbedPane1.addTab("Documents", documentsPane);

        jTabbedPane1.setSelectedIndex(1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 850, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTabbedPane1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseExited
        // TODO add your handling code here:
        floater.hide();
        deskPane.repaint();
    }//GEN-LAST:event_jTabbedPane1MouseExited

    private void fontListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_fontListValueChanged
        // TODO add your handling code here:
        int style = 0;
        if (((String) foneType.getSelectedItem()).equals("Plain")) {
            style = Font.PLAIN;
        } else if (((String) foneType.getSelectedItem()).equals("Bold")) {
            style = Font.BOLD;
        } else if (((String) foneType.getSelectedItem()).equals("Italic")) {
            style = Font.ITALIC;
        }
        if (((String) foneType.getSelectedItem()).equals("Bold/Italic")) {
            style = Font.BOLD & Font.ITALIC;
        }
        fontShow.setFont(new Font((String) fontList.getSelectedValue(), style, (int) (fontSize.getValue())));
    }//GEN-LAST:event_fontListValueChanged

    private void fontSizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fontSizeMouseClicked
        // TODO add your handling code here:
        int style = 0;
        if (((String) foneType.getSelectedItem()).equals("Plain")) {
            style = Font.PLAIN;
        } else if (((String) foneType.getSelectedItem()).equals("Bold")) {
            style = Font.BOLD;
        } else if (((String) foneType.getSelectedItem()).equals("Italic")) {
            style = Font.ITALIC;
        }
        if (((String) foneType.getSelectedItem()).equals("Bold/Italic")) {
            style = Font.BOLD & Font.ITALIC;
        }
        fontShow.setFont(new Font((String) fontList.getSelectedValue(), style, (int) (fontSize.getValue())));
    }//GEN-LAST:event_fontSizeMouseClicked

    private void foneTypeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_foneTypeItemStateChanged
        // TODO add your handling code here:
        int style = 0;
        if (((String) foneType.getSelectedItem()).equals("Plain")) {
            style = Font.PLAIN;
        } else if (((String) foneType.getSelectedItem()).equals("Bold")) {
            style = Font.BOLD;
        } else if (((String) foneType.getSelectedItem()).equals("Italic")) {
            style = Font.ITALIC;
        }
        if (((String) foneType.getSelectedItem()).equals("Bold/Italic")) {
            style = Font.BOLD & Font.ITALIC;
        }
        fontShow.setFont(new Font((String) fontList.getSelectedValue(), style, (int) (fontSize.getValue())));
    }//GEN-LAST:event_foneTypeItemStateChanged

    private void logInUserPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_logInUserPasswordKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            Diary3.logIn(logInUserName.getText(), logInUserPassword.getPassword());
            if (Diary3.CURRENT_USER.LOGGED_IN) {
                initUser(Diary3.CURRENT_USER);
                logInWindow.hide();
                floaterLogInButton.setBackground(new Color(255, 204, 204));
                floaterLogInButton.setText("Log Out");
                floaterLogInButton.setToolTipText("LOGOUT");
                logCalendar.fillDates();
                logEditorWindow.show();
                calendar.show();
                floater.hide();
                floaterUserNameDisplay.setText(Diary3.CURRENT_USER.USERNAME);
                this.repaint();
                financeManager2.setUSER(Diary3.CURRENT_USER);
            }
        }
    }//GEN-LAST:event_logInUserPasswordKeyPressed

    private void logInUserNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_logInUserNameKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            r.keyPress(KeyEvent.VK_TAB);
            r.keyRelease(KeyEvent.VK_TAB);
        }
    }//GEN-LAST:event_logInUserNameKeyPressed

    private void menuMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_menuMouseWheelMoved
        // TODO add your handling code here:
        int r = (int) ((Math.abs(evt.getUnitsToScroll()) / evt.getUnitsToScroll()));
        r = (menu.getSelectedIndex() + r) % menu.getTabCount();
        System.out.println(r);
        if (r >= 0) {
            menu.setSelectedIndex(r);
        } else {
            menu.setSelectedIndex(menu.getTabCount() + r);
        }
    }//GEN-LAST:event_menuMouseWheelMoved

    private void floaterLogInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_floaterLogInButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_floaterLogInButtonActionPerformed

    private void floaterLogInButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_floaterLogInButtonMouseClicked
        // TODO add your handling code here:
        if (Diary3.CURRENT_USER == null || !Diary3.CURRENT_USER.LOGGED_IN) {
            logInWindow.show();
            reset();

            floaterLogInButton.setBackground(new Color(153, 255, 153));
            floaterLogInButton.setText("Log In");
            floaterLogInButton.setToolTipText("LOGIN");
            logInUserPassword.setText("");
            desk.repaint();
        } else {
            reset();
            Diary3.CURRENT_USER = null;

            floaterLogInButton.setBackground(new Color(153, 255, 153));
            floaterLogInButton.setText("Log In");
            floaterLogInButton.setToolTipText("LOGIN");
            logInUserPassword.setText("");
            desk.repaint();
        }
    }//GEN-LAST:event_floaterLogInButtonMouseClicked

    private void floaterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_floaterMouseExited
        // TODO add your handling code here:
        System.out.println(evt.getY());
        if (evt.getY() > floater.getHeight() && !jToggleButton1.isSelected()) {
            floater.hide();
        }
        deskPane.repaint();
    }//GEN-LAST:event_floaterMouseExited
    boolean deskChangerRunning;
    int delay = 2000;

    private void deskMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deskMouseMoved
        // TODO add your handling code here:
        deskPane.repaint();
    }//GEN-LAST:event_deskMouseMoved

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void deskPaneMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deskPaneMouseMoved
        // TODO add your handling code here:
        deskPane.repaint();
        floater.setBounds(floater.getX(), floater.getY(), deskPane.getWidth(), floater.getHeight());
        if (!floater.isVisible()) {
            floater.setVisible(evt.getY() < 5);
        } else {
            floater.setVisible(evt.getY() < floater.getHeight());
        }
        if (jToggleButton1.isSelected()) {
            floater.show();
        }
    }//GEN-LAST:event_deskPaneMouseMoved

    private void logEditorMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logEditorMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_logEditorMouseMoved

    private void fontSize1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fontSize1MouseClicked
        int style = 0;
        if (((String) foneType1.getSelectedItem()).equals("Plain")) {
            style = Font.PLAIN;
        } else if (((String) foneType1.getSelectedItem()).equals("Bold")) {
            style = Font.BOLD;
        } else if (((String) foneType1.getSelectedItem()).equals("Italic")) {
            style = Font.ITALIC;
        }
        if (((String) foneType1.getSelectedItem()).equals("Bold/Italic")) {
            style = Font.BOLD & Font.ITALIC;
        }
        documentEditor1.SEL_FACE = (String) fontList1.getSelectedValue();
        documentEditor1.SEL_TYPE = (String) foneType1.getSelectedItem();
        documentEditor1.SEL_SIZE = (int) (fontSize1.getValue()) + "";
        documentEditor1.SEL_COLOR = fontColor1.getText();
        documentEditor1.addToken();
        fontShow1.setFont(new Font((String) fontList1.getSelectedValue(), style, (int) (fontSize1.getValue())));
        documentEditor1.setFont(fontShow1.getFont());
    }//GEN-LAST:event_fontSize1MouseClicked

    private void foneType1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_foneType1ItemStateChanged
        int style = 0;
        if (((String) foneType1.getSelectedItem()).equals("Plain")) {
            style = Font.PLAIN;
        } else if (((String) foneType1.getSelectedItem()).equals("Bold")) {
            style = Font.BOLD;
        } else if (((String) foneType1.getSelectedItem()).equals("Italic")) {
            style = Font.ITALIC;
        }
        if (((String) foneType1.getSelectedItem()).equals("Bold/Italic")) {
            style = Font.BOLD & Font.ITALIC;
        }
        documentEditor1.SEL_FACE = (String) fontList1.getSelectedValue();
        documentEditor1.SEL_TYPE = (String) foneType1.getSelectedItem();
        documentEditor1.SEL_SIZE = (int) (fontSize1.getValue()) + "";
        documentEditor1.SEL_COLOR = fontColor1.getText();
        documentEditor1.addToken();
        fontShow1.setFont(new Font((String) fontList1.getSelectedValue(), style, (int) (fontSize1.getValue())));
        documentEditor1.setFont(fontShow1.getFont());
    }//GEN-LAST:event_foneType1ItemStateChanged

    private void fontList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_fontList1ValueChanged
        int style = 0;
        if (((String) foneType1.getSelectedItem()).equals("Plain")) {
            style = Font.PLAIN;
        } else if (((String) foneType1.getSelectedItem()).equals("Bold")) {
            style = Font.BOLD;
        } else if (((String) foneType1.getSelectedItem()).equals("Italic")) {
            style = Font.ITALIC;
        }
        if (((String) foneType1.getSelectedItem()).equals("Bold/Italic")) {
            style = Font.BOLD & Font.ITALIC;
        }
        documentEditor1.SEL_FACE = (String) fontList1.getSelectedValue();
        documentEditor1.SEL_TYPE = (String) foneType1.getSelectedItem();
        documentEditor1.SEL_SIZE = (int) (fontSize1.getValue()) + "";
        documentEditor1.SEL_COLOR = fontColor1.getText();
        documentEditor1.addToken();
        fontShow1.setFont(new Font((String) fontList1.getSelectedValue(), style, (int) (fontSize1.getValue())));
        documentEditor1.setFont(fontShow1.getFont());
    }//GEN-LAST:event_fontList1ValueChanged

    private void logEditorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logEditorMouseClicked
        // TODO add your handling code here:
        if (evt.getButton() == MouseEvent.BUTTON3) {
            if (floater.isVisible()) {
                floater.hide();
            } else {
                floater.show();
            }
            menu.setSelectedIndex(2);
        }
    }//GEN-LAST:event_logEditorMouseClicked

    private void addLogButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addLogButtonActionPerformed
        // TODO add your handling code here:
        Diary3.CURRENT_USER.addLogForCurrentTime(documentEditor1.getText(),titleView.getText());
        System.out.println("Done : " + new Date());
        logCalendar.refreshList();
    }//GEN-LAST:event_addLogButtonActionPerformed

    private void currentLogListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_currentLogListValueChanged
        // TODO add your handling code here:
        logEditor.setText(Diary3.CURRENT_USER.readSelectedLog());
        documentEditor1.setText(Diary3.CURRENT_USER.readSelectedLog().replaceAll("\n", "<br>"));
        String n = (String) (currentLogList.getSelectedValue());
        if (n.contains(".logx")) {
            n = n.substring(0, n.lastIndexOf(".logx"));
        }
        String time = n.substring(0, n.indexOf("."));
        StringTokenizer st = new StringTokenizer(time, "-");
        String h = (st.nextToken());
        String m = (st.nextToken());
        String s = (st.nextToken());
        String title = n.substring(n.indexOf(".") + 1);
        title = new JuliusCrypter().perfectSquareCrypt(title);
        String yr = logCalendar.years.getSelectedItem().toString();
        String mth = (logCalendar.months.getSelectedIndex() + 1) + "";
        int x = logCalendar.dates.getSelectedRow();
        int y = logCalendar.dates.getSelectedColumn();
        final String value = (String) logCalendar.dates.getModel().getValueAt(x, y);
        String date = value.substring(0, value.indexOf(" ")).trim();
        int hi = Integer.parseInt(h);
        int mi = Integer.parseInt(m);
        int si = Integer.parseInt(s);
        int yi = Integer.parseInt(yr);
        int moi = Integer.parseInt(mth);
        int di = Integer.parseInt(date);
        Date d = new Date(yi, moi, di, hi, mi-1, si);
        titleView.setText(title);
        logEditorWindow.setTitle(d.toString()+" - "+title);
        desk.repaint();
    }//GEN-LAST:event_currentLogListValueChanged

    private void currentLogListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_currentLogListMouseClicked
        // TODO add your handling code here:
        logEditor.setText(Diary3.CURRENT_USER.readSelectedLog());
        desk.repaint();
    }//GEN-LAST:event_currentLogListMouseClicked

    private void fontSize1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_fontSize1PropertyChange
        System.out.println("Do");
    }//GEN-LAST:event_fontSize1PropertyChange

    private void fontSize1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_fontSize1StateChanged
        // TODO add your handling code here:
        System.out.println("Do");
        int style = 0;
        if (((String) foneType1.getSelectedItem()).equals("Plain")) {
            style = Font.PLAIN;
        } else if (((String) foneType1.getSelectedItem()).equals("Bold")) {
            style = Font.BOLD;
        } else if (((String) foneType1.getSelectedItem()).equals("Italic")) {
            style = Font.ITALIC;
        }
        if (((String) foneType1.getSelectedItem()).equals("Bold/Italic")) {
            style = Font.BOLD & Font.ITALIC;
        }
        documentEditor1.SEL_FACE = (String) fontList1.getSelectedValue();
        documentEditor1.SEL_TYPE = (String) foneType1.getSelectedItem();
        documentEditor1.SEL_SIZE = (int) (fontSize1.getValue()) + "";
        documentEditor1.SEL_COLOR = fontColor1.getText();
        documentEditor1.addToken();
        fontShow1.setFont(new Font((String) fontList1.getSelectedValue(), style, (int) (fontSize1.getValue())));
        documentEditor1.setFont(fontShow1.getFont());
    }//GEN-LAST:event_fontSize1StateChanged

    private void fontColor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fontColor1ActionPerformed

        documentEditor1.SEL_FACE = (String) fontList1.getSelectedValue();
        documentEditor1.SEL_TYPE = (String) foneType1.getSelectedItem();
        documentEditor1.SEL_SIZE = (int) (fontSize1.getValue()) + "";
        documentEditor1.SEL_COLOR = fontColor1.getText();
        documentEditor1.addToken();        // TODO add your handling code here:
    }//GEN-LAST:event_fontColor1ActionPerformed

    private void addLogButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addLogButton1ActionPerformed
        // TODO add your handling code here:
        documentEditor1.CURRENTLY_EDITING.STRING += htmlCodeEditor.getText();
        documentEditor1.refresh();
    }//GEN-LAST:event_addLogButton1ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        htmlCodeEditor.setText(htmlCodeEditor.getText() + jButton9.getToolTipText());
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:

        htmlCodeEditor.setText(htmlCodeEditor.getText() + jButton8.getToolTipText());
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        htmlCodeEditor.setText(htmlCodeEditor.getText() + jButton1.getToolTipText());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        htmlCodeEditor.setText(htmlCodeEditor.getText() + jButton2.getToolTipText());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        htmlCodeEditor.setText(htmlCodeEditor.getText() + jButton10.getToolTipText());
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        htmlCodeEditor.setText(htmlCodeEditor.getText() + jButton11.getToolTipText());
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        htmlCodeEditor.setText(htmlCodeEditor.getText() + jButton12.getToolTipText());
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        // TODO add your handling code here:
        int t = (jComboBox1.getSelectedIndex() + 1);
        htmlCodeEditor.setText(htmlCodeEditor.getText() + " <h" + t + "> </h" + t + ">");
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        setEditMenu("HTML");
    }//GEN-LAST:event_jButton13ActionPerformed

    private void themesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_themesValueChanged
        // TODO add your handling code here:
        String s = (String) themes.getSelectedValue();
        System.out.println(s);
        try {
            UIManager.setLookAndFeel(s);
            System.out.println("Changed");
            repaint();
            SwingUtilities.updateComponentTreeUI(this);
            this.pack();
            GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
            this.setBounds(ge.getMaximumWindowBounds());
            repaint();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(DiaryView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(DiaryView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(DiaryView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(DiaryView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_themesValueChanged

    private void documentsPaneMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_documentsPaneMouseWheelMoved
        // TODO add your handling code here:
        int r = (int) ((Math.abs(evt.getUnitsToScroll()) / evt.getUnitsToScroll()));
        r = (documentsPane.getSelectedIndex() + r) % documentsPane.getTabCount();
        System.out.println(r);
        if (r >= 0) {
            documentsPane.setSelectedIndex(r);
        } else {
            documentsPane.setSelectedIndex(documentsPane.getTabCount() + r);
        }
    }//GEN-LAST:event_documentsPaneMouseWheelMoved
    Robot r;
    Timer t;

    public void refreshCalendar() {
        logCalendar.fillDates();
        logCalendar.refreshList();
    }

    public void setEditMenu(String code) {
        System.out.println("enter");
        if (code.equals("Edit")) {
            editMenu.removeAll();
            editMenu.setLayout(new GridLayout());
            editMenu.add(defaultEditMenu);
            defaultEditMenu.show();
            System.out.println("done");
        } else if (code.equals("User")) {
            menu.setSelectedIndex(0);
            floater.show();
            System.out.println("done user");
            return;
        } else if (code.equals("Desk")) {
            editMenu.removeAll();
            editMenu.setLayout(new GridLayout());
            editMenu.add(deskEditMenu);
            deskEditMenu.show();
            System.out.println("done");
        } else if (code.equals("Log")) {
            editMenu.removeAll();
            editMenu.setLayout(new GridLayout());
            editMenu.add(logEditMenu);
            deskEditMenu.show();
            System.out.println("done");
        } else if (code.equals("HTML")) {
            logEditTab.setSelectedIndex(1);
            floater.show();
            System.out.println("done user");
            return;
        } else if (code.equals("None")) {
            editMenu.removeAll();
        }
        floater.show();
        menu.setSelectedIndex(2);
    }

    public void setCurrentComponent(Component c) {
        CURRENT_COMPONENT = c;
    }

    private static BufferedImage resizeImage(BufferedImage originalImage, int type,
            Integer img_width, Integer img_height) {
        BufferedImage resizedImage = new BufferedImage(img_width, img_height, type);
        Graphics g = resizedImage.createGraphics();
        g.drawImage(originalImage, 0, 0, img_width, img_height, null);
        g.dispose();

        return resizedImage;
    }

    private static Image resizeImage(Image originalImage,
            Integer img_width, Integer img_height) {
        Image resizedImage = new BufferedImage(img_width, img_height, BufferedImage.TYPE_INT_RGB);
        Graphics g = resizedImage.getGraphics();
        g.drawImage(originalImage, 0, 0, img_width, img_height, null);
        g.dispose();

        return resizedImage;
    }
    private Image img;
    private int wallIndex;

    private void reset() {
        logEditorWindow.hide();
        logInWindow.show();
        calendar.hide();
    }

    public void set() {
        logInWindow.hide();
        logEditorWindow.show();
        calendar.show();
    }
    private java.awt.Component CURRENT_COMPONENT;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLayeredPane Others;
    public javax.swing.JButton addLogButton;
    public javax.swing.JButton addLogButton1;
    public javax.swing.JLabel bd_address;
    public javax.swing.JLabel bd_brief;
    public javax.swing.JLabel bd_city;
    public javax.swing.JLabel bd_country;
    public javax.swing.JLabel bd_dob;
    public javax.swing.JLabel bd_first_name;
    public javax.swing.JLabel bd_gender;
    public javax.swing.JLabel bd_last_name;
    public javax.swing.JLabel bd_middle_name;
    public javax.swing.JLabel bd_mobile_number;
    public javax.swing.JLabel bd_phone_number;
    public javax.swing.JLabel bd_pin_code;
    public javax.swing.JLabel bd_region_province;
    public javax.swing.JLabel bd_relationship_status;
    public javax.swing.JLabel bd_username;
    public javax.swing.JPanel biodata;
    public javax.swing.JInternalFrame calendar;
    public javax.swing.JList currentLogList;
    public javax.swing.JPanel defaultEditMenu;
    public javax.swing.JPanel desk;
    public javax.swing.JPanel deskEditMenu;
    public javax.swing.JDesktopPane deskPane;
    public diary3.DocumentEditor documentEditor1;
    public javax.swing.JTabbedPane documentsPane;
    public javax.swing.JPanel editMenu;
    public javax.swing.JPanel fileMenu;
    public diary3.financemanager.FinanceManager financeManager2;
    public javax.swing.JPanel floater;
    public javax.swing.JButton floaterLogInButton;
    public javax.swing.JLabel floaterUserNameDisplay;
    public javax.swing.JComboBox foneType;
    public javax.swing.JComboBox foneType1;
    public javax.swing.JTextField fontColor1;
    public javax.swing.JList fontList;
    public javax.swing.JList fontList1;
    public javax.swing.JLabel fontShow;
    public javax.swing.JLabel fontShow1;
    public javax.swing.JSpinner fontSize;
    public javax.swing.JSpinner fontSize1;
    public javax.swing.JPanel home;
    public javax.swing.JTextPane htmlCodeEditor;
    public javax.swing.JButton jButton1;
    public javax.swing.JButton jButton10;
    public javax.swing.JButton jButton11;
    public javax.swing.JButton jButton12;
    public javax.swing.JButton jButton13;
    public javax.swing.JButton jButton2;
    public javax.swing.JButton jButton3;
    public javax.swing.JButton jButton4;
    public javax.swing.JButton jButton5;
    public javax.swing.JButton jButton6;
    public javax.swing.JButton jButton7;
    public javax.swing.JButton jButton8;
    public javax.swing.JButton jButton9;
    public javax.swing.JComboBox jComboBox1;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    public javax.swing.JPanel jPanel3;
    public javax.swing.JPanel jPanel4;
    public javax.swing.JPanel jPanel5;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JScrollPane jScrollPane10;
    public javax.swing.JScrollPane jScrollPane11;
    public javax.swing.JScrollPane jScrollPane12;
    public javax.swing.JScrollPane jScrollPane14;
    public javax.swing.JScrollPane jScrollPane15;
    public javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JScrollPane jScrollPane4;
    public javax.swing.JScrollPane jScrollPane5;
    public javax.swing.JScrollPane jScrollPane6;
    public javax.swing.JScrollPane jScrollPane7;
    public javax.swing.JScrollPane jScrollPane8;
    public javax.swing.JScrollPane jScrollPane9;
    public javax.swing.JTabbedPane jTabbedPane1;
    public javax.swing.JToggleButton jToggleButton1;
    public javax.swing.JToolBar jToolBar1;
    public diary3.DCalendar logCalendar;
    public javax.swing.JPanel logEditMenu;
    public javax.swing.JTabbedPane logEditTab;
    public javax.swing.JEditorPane logEditor;
    public javax.swing.JInternalFrame logEditorWindow;
    public javax.swing.JTextField logInUserName;
    public javax.swing.JPasswordField logInUserPassword;
    public javax.swing.JInternalFrame logInWindow;
    public javax.swing.JPanel managementMenu;
    public javax.swing.JTabbedPane menu;
    public javax.swing.JDesktopPane musicPane;
    public javax.swing.JDesktopPane picturesPane;
    public javax.swing.JList themes;
    public javax.swing.JTextField titleView;
    public javax.swing.JPanel userMenu;
    // End of variables declaration//GEN-END:variables

    private void initUser(User CURRENT_USER) {
    }

    void setBioData(BioData bioData) {
        bd_username.setText("Username : " + bioData.USERNAME);
        bd_first_name.setText("First Name : " + bioData.FIRST_NAME);
        bd_middle_name.setText("Middle Name : " + bioData.MIDDLE_NAME);
        bd_last_name.setText("Last Name : " + bioData.LAST_NAME);
        bd_gender.setText("Gender : " + bioData.GENDER);
        bd_dob.setText("Date of Birth : " + bioData.DOB);
        bd_address.setText("Address : " + bioData.ADDRESS);
        bd_city.setText("City : " + bioData.CITY);
        bd_region_province.setText("Region/Province : " + bioData.REGION_PROVINCE);
        bd_country.setText("Country : " + bioData.COUNTRY);
        bd_pin_code.setText("Pin Code : " + bioData.PIN_CODE);
        bd_phone_number.setText("Phone Number : " + bioData.PHONE_NUMBER);
        bd_mobile_number.setText("Mobile Number : " + bioData.MOBILE_NUMBER);
        bd_relationship_status.setText("Relationship Status : " + bioData.RELATIONSHIP_STATUS);
        bd_brief.setText("Brief : " + bioData.BRIEF);
    }
}
